name: Build BIOS Tracker

on:
  push:
  schedule:
    - cron: '17 3 * * *'  # nightly UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build site
        run: |
          python bios_tracker.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/index.html docs/data.json || true
          git commit -m "Update BIOS site [skip ci]" || echo "No changes"
          git push
