asus:
  - ROG Strix Z790-E Gaming WiFi
  - PRIME B550-PLUS
msi:
  - MPG B550 GAMING EDGE WIFI
  - MAG Z790 TOMAHAWK WIFI
gigabyte:
  - B550 AORUS ELITE
  - Z790 AORUS MASTER
asrock:
  - B550 Taichi
  - Z790 PG Lightning
