name: Build & Push /docs

on:
  schedule:
    - cron: "0 10 * * 1-5"
  workflow_dispatch:        # run on-demand from the Actions tab

permissions:
  contents: write           # needed to push updates to /docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Build site (writes to docs/)
        run: |
          mkdir -p docs
          xvfb-run -a python bios_tracker.py
          touch docs/.nojekyll

      - name: Commit & push /docs (always)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A docs
          git commit --allow-empty -m "docs: refresh site ($(date -u +'%Y-%m-%d %H:%M UTC'))"
          git push
