name: Build & Push docs (GitHub Pages)

on:
  schedule:
    # ~5:00 AM America/Chicago during DST; adjust if you want winter to be closer to 5:00
    - cron: "0 10 * * 1-5"
  workflow_dispatch:

# We commit back to the repo, so we need write
permissions:
  contents: write

concurrency:
  group: docs-build
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     # allow rebasing before push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      # Build your site; xvfb-run lets Playwright fallback to "headful" if needed
      - name: Build site
        run: |
          xvfb-run -a python bios_tracker.py
          touch docs/.nojekyll   # ensure Jekyll doesn't interfere

      - name: Configure Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Rebase in case of concurrent pushes, then commit only if docs changed
      - name: Commit & Push docs
        run: |
          # Pull latest for this branch
          git pull --rebase --autostash origin "${GITHUB_REF_NAME}"

          # Ensure docs/ exists and add it
          git add docs

