name: Build & Push docs (GitHub Pages)

on:
  schedule:
    # ~5:00 AM America/Chicago during DST; adjust if you want winter to be closer to 5:00
    - cron: "0 10 * * 1-5"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout@v3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tracker
        run: python bios_tracker.py
        
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/*
          git commit -m "Update BIOS data" || echo "No changes"
          git push

