name: Scrape BIOS
on:
  schedule:
    - cron: "15 5 * * *"  # daily at 05:15 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python -m src.scrape
      - name: Commit changes
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add docs/data.json
          git commit -m "Update BIOS data [skip ci]" || echo "No changes"
          git push
